-- Auto-generated by clone-blocks-schema.py on 2026-04-20
-- Clones the concerns_blocks_* page-block sub-tables to lps_blocks_*
-- so the lps collection can render pageBlocks.
--
-- WHY: commit e18bdb8 (feat(cms): add pageBlocks to Costs/LandingPages/Lps)
-- added the shared ALL_PAGE_BLOCKS field to the lps collection in
-- Payload config, but the matching DB tables were never created. Payload
-- falls over with 500 when you fetch lps at depth>=1 because it tries
-- to LEFT JOIN block tables that don't exist.
--
-- Source: pg_dump of cms.concerns_blocks_* + cms._concerns_v_blocks_*
-- (34 tables + 34 version tables + FK constraints + indexes + sequences).
--
-- Safe to re-run? NO — contains CREATE TABLE without IF NOT EXISTS.
-- Run once per collection; the migration pipeline tracks applied migrations.

BEGIN;

-- Enum types the benefits_block and content_grid blocks need for their
-- `icon` column. Values mirror the concerns variant of each type.
CREATE TYPE cms.enum_lps_blocks_benefits_block_items_icon AS ENUM (
    'shield','stethoscope','sun','heart','zap','sparkles','tech',
    'doctors','results','experience','award','check','clock','leaf'
);
CREATE TYPE cms.enum__lps_v_blocks_benefits_block_items_icon AS ENUM (
    'shield','stethoscope','sun','heart','zap','sparkles','tech',
    'doctors','results','experience','award','check','clock','leaf'
);
CREATE TYPE cms.enum_lps_blocks_content_grid_items_icon AS ENUM (
    'shield','stethoscope','sun','heart','zap','sparkles','tech',
    'doctors','results','experience','award','check','clock','leaf'
);
CREATE TYPE cms.enum__lps_v_blocks_content_grid_items_icon AS ENUM (
    'shield','stethoscope','sun','heart','zap','sparkles','tech',
    'doctors','results','experience','award','check','clock','leaf'
);








CREATE TABLE cms._lps_v_blocks_before_after_block (
    _order integer NOT NULL,
    _parent_id integer NOT NULL,
    _path text NOT NULL,
    id integer NOT NULL,
    eyebrow character varying,
    heading character varying,
    _uuid character varying,
    block_name character varying
);



CREATE SEQUENCE cms._lps_v_blocks_before_after_block_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;



ALTER SEQUENCE cms._lps_v_blocks_before_after_block_id_seq OWNED BY cms._lps_v_blocks_before_after_block.id;



CREATE TABLE cms._lps_v_blocks_before_after_block_items (
    _order integer NOT NULL,
    _parent_id integer NOT NULL,
    id integer NOT NULL,
    title character varying,
    before_image_url character varying,
    after_image_url character varying,
    caption character varying,
    _uuid character varying
);



CREATE SEQUENCE cms._lps_v_blocks_before_after_block_items_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;



ALTER SEQUENCE cms._lps_v_blocks_before_after_block_items_id_seq OWNED BY cms._lps_v_blocks_before_after_block_items.id;



CREATE TABLE cms._lps_v_blocks_benefits_block (
    _order integer NOT NULL,
    _parent_id integer NOT NULL,
    _path text NOT NULL,
    id integer NOT NULL,
    eyebrow character varying,
    heading character varying,
    _uuid character varying,
    block_name character varying
);



CREATE SEQUENCE cms._lps_v_blocks_benefits_block_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;



ALTER SEQUENCE cms._lps_v_blocks_benefits_block_id_seq OWNED BY cms._lps_v_blocks_benefits_block.id;



CREATE TABLE cms._lps_v_blocks_benefits_block_items (
    _order integer NOT NULL,
    _parent_id integer NOT NULL,
    id integer NOT NULL,
    title character varying,
    description character varying,
    icon cms.enum__lps_v_blocks_benefits_block_items_icon DEFAULT 'shield'::cms.enum__lps_v_blocks_benefits_block_items_icon,
    _uuid character varying
);



CREATE SEQUENCE cms._lps_v_blocks_benefits_block_items_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;



ALTER SEQUENCE cms._lps_v_blocks_benefits_block_items_id_seq OWNED BY cms._lps_v_blocks_benefits_block_items.id;



CREATE TABLE cms._lps_v_blocks_booking_form (
    _order integer NOT NULL,
    _parent_id integer NOT NULL,
    _path text NOT NULL,
    id integer NOT NULL,
    eyebrow character varying,
    heading character varying DEFAULT 'Book Your Consultation'::character varying,
    cta_label character varying DEFAULT 'Book FREE Consultation'::character varying,
    _uuid character varying,
    block_name character varying
);



CREATE SEQUENCE cms._lps_v_blocks_booking_form_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;



ALTER SEQUENCE cms._lps_v_blocks_booking_form_id_seq OWNED BY cms._lps_v_blocks_booking_form.id;



CREATE TABLE cms._lps_v_blocks_content_grid (
    _order integer NOT NULL,
    _parent_id integer NOT NULL,
    _path text NOT NULL,
    id integer NOT NULL,
    eyebrow character varying,
    heading character varying,
    columns cms."gridCols" DEFAULT '2'::cms."gridCols",
    _uuid character varying,
    block_name character varying
);



CREATE SEQUENCE cms._lps_v_blocks_content_grid_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;



ALTER SEQUENCE cms._lps_v_blocks_content_grid_id_seq OWNED BY cms._lps_v_blocks_content_grid.id;



CREATE TABLE cms._lps_v_blocks_content_grid_items (
    _order integer NOT NULL,
    _parent_id integer NOT NULL,
    id integer NOT NULL,
    title character varying,
    description character varying,
    image_url character varying,
    image_alt_text character varying,
    href character varying,
    icon cms.enum__lps_v_blocks_content_grid_items_icon,
    _uuid character varying
);



CREATE SEQUENCE cms._lps_v_blocks_content_grid_items_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;



ALTER SEQUENCE cms._lps_v_blocks_content_grid_items_id_seq OWNED BY cms._lps_v_blocks_content_grid_items.id;



CREATE TABLE cms._lps_v_blocks_cta_block (
    _order integer NOT NULL,
    _parent_id integer NOT NULL,
    _path text NOT NULL,
    id integer NOT NULL,
    heading character varying,
    description character varying,
    primary_cta_label character varying,
    primary_cta_href character varying,
    secondary_cta_label character varying,
    secondary_cta_href character varying,
    variant cms."ctaVariant" DEFAULT 'dark'::cms."ctaVariant",
    _uuid character varying,
    block_name character varying
);



CREATE SEQUENCE cms._lps_v_blocks_cta_block_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;



ALTER SEQUENCE cms._lps_v_blocks_cta_block_id_seq OWNED BY cms._lps_v_blocks_cta_block.id;



CREATE TABLE cms._lps_v_blocks_data_table (
    _order integer NOT NULL,
    _parent_id integer NOT NULL,
    _path text NOT NULL,
    id integer NOT NULL,
    eyebrow character varying,
    heading character varying,
    caption character varying,
    _uuid character varying,
    block_name character varying
);



CREATE TABLE cms._lps_v_blocks_data_table_columns (
    _order integer NOT NULL,
    _parent_id integer NOT NULL,
    id integer NOT NULL,
    key character varying,
    label character varying,
    align cms.align DEFAULT 'left'::cms.align,
    highlight boolean,
    _uuid character varying
);



CREATE SEQUENCE cms._lps_v_blocks_data_table_columns_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;



ALTER SEQUENCE cms._lps_v_blocks_data_table_columns_id_seq OWNED BY cms._lps_v_blocks_data_table_columns.id;



CREATE SEQUENCE cms._lps_v_blocks_data_table_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;



ALTER SEQUENCE cms._lps_v_blocks_data_table_id_seq OWNED BY cms._lps_v_blocks_data_table.id;



CREATE TABLE cms._lps_v_blocks_data_table_rows (
    _order integer NOT NULL,
    _parent_id integer NOT NULL,
    id integer NOT NULL,
    _uuid character varying
);



CREATE TABLE cms._lps_v_blocks_data_table_rows_cells (
    _order integer NOT NULL,
    _parent_id integer NOT NULL,
    id integer NOT NULL,
    key character varying,
    value character varying,
    _uuid character varying
);



CREATE SEQUENCE cms._lps_v_blocks_data_table_rows_cells_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;



ALTER SEQUENCE cms._lps_v_blocks_data_table_rows_cells_id_seq OWNED BY cms._lps_v_blocks_data_table_rows_cells.id;



CREATE SEQUENCE cms._lps_v_blocks_data_table_rows_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;



ALTER SEQUENCE cms._lps_v_blocks_data_table_rows_id_seq OWNED BY cms._lps_v_blocks_data_table_rows.id;



CREATE TABLE cms._lps_v_blocks_doctors_embed (
    _order integer NOT NULL,
    _parent_id integer NOT NULL,
    _path text NOT NULL,
    id integer NOT NULL,
    eyebrow character varying,
    heading character varying,
    "limit" numeric DEFAULT 6,
    filter_by_content_category_id integer,
    _uuid character varying,
    block_name character varying
);



CREATE SEQUENCE cms._lps_v_blocks_doctors_embed_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;



ALTER SEQUENCE cms._lps_v_blocks_doctors_embed_id_seq OWNED BY cms._lps_v_blocks_doctors_embed.id;



CREATE TABLE cms._lps_v_blocks_faqs_embed (
    _order integer NOT NULL,
    _parent_id integer NOT NULL,
    _path text NOT NULL,
    id integer NOT NULL,
    eyebrow character varying,
    heading character varying,
    filter_by_content_category_id integer,
    _uuid character varying,
    block_name character varying
);



CREATE SEQUENCE cms._lps_v_blocks_faqs_embed_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;



ALTER SEQUENCE cms._lps_v_blocks_faqs_embed_id_seq OWNED BY cms._lps_v_blocks_faqs_embed.id;



CREATE TABLE cms._lps_v_blocks_faqs_embed_inline_faqs (
    _order integer NOT NULL,
    _parent_id integer NOT NULL,
    id integer NOT NULL,
    question character varying,
    answer character varying,
    _uuid character varying
);



CREATE SEQUENCE cms._lps_v_blocks_faqs_embed_inline_faqs_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;



ALTER SEQUENCE cms._lps_v_blocks_faqs_embed_inline_faqs_id_seq OWNED BY cms._lps_v_blocks_faqs_embed_inline_faqs.id;



CREATE TABLE cms._lps_v_blocks_html_embed (
    id integer NOT NULL,
    _parent_id integer NOT NULL,
    _order integer NOT NULL,
    _path text NOT NULL,
    heading character varying,
    code character varying,
    _uuid character varying,
    block_name character varying
);



CREATE SEQUENCE cms._lps_v_blocks_html_embed_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;



ALTER SEQUENCE cms._lps_v_blocks_html_embed_id_seq OWNED BY cms._lps_v_blocks_html_embed.id;



CREATE TABLE cms._lps_v_blocks_image_slider (
    _order integer NOT NULL,
    _parent_id integer NOT NULL,
    _path text NOT NULL,
    id integer NOT NULL,
    eyebrow character varying,
    heading character varying,
    aspect_ratio cms."aspectRatio" DEFAULT '16/9'::cms."aspectRatio",
    autoplay_ms numeric DEFAULT 0,
    _uuid character varying,
    block_name character varying
);



CREATE SEQUENCE cms._lps_v_blocks_image_slider_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;



ALTER SEQUENCE cms._lps_v_blocks_image_slider_id_seq OWNED BY cms._lps_v_blocks_image_slider.id;



CREATE TABLE cms._lps_v_blocks_image_slider_images (
    _order integer NOT NULL,
    _parent_id integer NOT NULL,
    id integer NOT NULL,
    image_url character varying,
    image_alt_text character varying,
    caption character varying,
    _uuid character varying
);



CREATE SEQUENCE cms._lps_v_blocks_image_slider_images_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;



ALTER SEQUENCE cms._lps_v_blocks_image_slider_images_id_seq OWNED BY cms._lps_v_blocks_image_slider_images.id;



CREATE TABLE cms._lps_v_blocks_notice_block (
    _order integer NOT NULL,
    _parent_id integer NOT NULL,
    _path text NOT NULL,
    _uuid character varying,
    id integer NOT NULL,
    variant character varying,
    icon character varying,
    heading character varying,
    body character varying,
    block_name character varying
);



CREATE SEQUENCE cms._lps_v_blocks_notice_block_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;



ALTER SEQUENCE cms._lps_v_blocks_notice_block_id_seq OWNED BY cms._lps_v_blocks_notice_block.id;



CREATE TABLE cms._lps_v_blocks_overview_block (
    _order integer NOT NULL,
    _parent_id integer NOT NULL,
    _path text NOT NULL,
    id integer NOT NULL,
    eyebrow character varying,
    heading character varying,
    _uuid character varying,
    block_name character varying
);



CREATE SEQUENCE cms._lps_v_blocks_overview_block_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;



ALTER SEQUENCE cms._lps_v_blocks_overview_block_id_seq OWNED BY cms._lps_v_blocks_overview_block.id;



CREATE TABLE cms._lps_v_blocks_overview_block_paragraphs (
    _order integer NOT NULL,
    _parent_id integer NOT NULL,
    id integer NOT NULL,
    text character varying,
    _uuid character varying
);



CREATE SEQUENCE cms._lps_v_blocks_overview_block_paragraphs_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;



ALTER SEQUENCE cms._lps_v_blocks_overview_block_paragraphs_id_seq OWNED BY cms._lps_v_blocks_overview_block_paragraphs.id;



CREATE TABLE cms._lps_v_blocks_pricing_block (
    _order integer NOT NULL,
    _parent_id integer NOT NULL,
    _path text NOT NULL,
    id integer NOT NULL,
    eyebrow character varying,
    heading character varying,
    _uuid character varying,
    block_name character varying
);



CREATE SEQUENCE cms._lps_v_blocks_pricing_block_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;



ALTER SEQUENCE cms._lps_v_blocks_pricing_block_id_seq OWNED BY cms._lps_v_blocks_pricing_block.id;



CREATE TABLE cms._lps_v_blocks_pricing_block_plans (
    _order integer NOT NULL,
    _parent_id integer NOT NULL,
    id integer NOT NULL,
    name character varying,
    price character varying,
    currency character varying DEFAULT '₹'::character varying,
    description character varying,
    highlighted boolean,
    badge character varying,
    cta_label character varying DEFAULT 'Book Now'::character varying,
    cta_href character varying DEFAULT '#booking'::character varying,
    _uuid character varying
);



CREATE TABLE cms._lps_v_blocks_pricing_block_plans_features (
    _order integer NOT NULL,
    _parent_id integer NOT NULL,
    id integer NOT NULL,
    value character varying,
    _uuid character varying
);



CREATE SEQUENCE cms._lps_v_blocks_pricing_block_plans_features_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;



ALTER SEQUENCE cms._lps_v_blocks_pricing_block_plans_features_id_seq OWNED BY cms._lps_v_blocks_pricing_block_plans_features.id;



CREATE SEQUENCE cms._lps_v_blocks_pricing_block_plans_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;



ALTER SEQUENCE cms._lps_v_blocks_pricing_block_plans_id_seq OWNED BY cms._lps_v_blocks_pricing_block_plans.id;



CREATE TABLE cms._lps_v_blocks_process_block (
    _order integer NOT NULL,
    _parent_id integer NOT NULL,
    _path text NOT NULL,
    id integer NOT NULL,
    eyebrow character varying,
    heading character varying,
    _uuid character varying,
    block_name character varying
);



CREATE SEQUENCE cms._lps_v_blocks_process_block_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;



ALTER SEQUENCE cms._lps_v_blocks_process_block_id_seq OWNED BY cms._lps_v_blocks_process_block.id;



CREATE TABLE cms._lps_v_blocks_process_block_steps (
    _order integer NOT NULL,
    _parent_id integer NOT NULL,
    id integer NOT NULL,
    title character varying,
    description character varying,
    _uuid character varying
);



CREATE SEQUENCE cms._lps_v_blocks_process_block_steps_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;



ALTER SEQUENCE cms._lps_v_blocks_process_block_steps_id_seq OWNED BY cms._lps_v_blocks_process_block_steps.id;



CREATE TABLE cms._lps_v_blocks_stats_block (
    _order integer NOT NULL,
    _parent_id integer NOT NULL,
    _path text NOT NULL,
    id integer NOT NULL,
    eyebrow character varying,
    heading character varying,
    variant cms."statsVariant" DEFAULT 'dark'::cms."statsVariant",
    _uuid character varying,
    block_name character varying
);



CREATE SEQUENCE cms._lps_v_blocks_stats_block_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;



ALTER SEQUENCE cms._lps_v_blocks_stats_block_id_seq OWNED BY cms._lps_v_blocks_stats_block.id;



CREATE TABLE cms._lps_v_blocks_stats_block_items (
    _order integer NOT NULL,
    _parent_id integer NOT NULL,
    id integer NOT NULL,
    value character varying,
    label character varying,
    suffix character varying,
    _uuid character varying
);



CREATE SEQUENCE cms._lps_v_blocks_stats_block_items_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;



ALTER SEQUENCE cms._lps_v_blocks_stats_block_items_id_seq OWNED BY cms._lps_v_blocks_stats_block_items.id;



CREATE TABLE cms._lps_v_blocks_takeaways_block (
    _order integer NOT NULL,
    _parent_id integer NOT NULL,
    _path text NOT NULL,
    _uuid character varying,
    id integer NOT NULL,
    heading character varying,
    block_name character varying
);



CREATE SEQUENCE cms._lps_v_blocks_takeaways_block_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;



ALTER SEQUENCE cms._lps_v_blocks_takeaways_block_id_seq OWNED BY cms._lps_v_blocks_takeaways_block.id;



CREATE TABLE cms._lps_v_blocks_takeaways_block_items (
    _order integer NOT NULL,
    _parent_id integer NOT NULL,
    _uuid character varying,
    id integer NOT NULL,
    text character varying
);



CREATE SEQUENCE cms._lps_v_blocks_takeaways_block_items_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;



ALTER SEQUENCE cms._lps_v_blocks_takeaways_block_items_id_seq OWNED BY cms._lps_v_blocks_takeaways_block_items.id;



CREATE TABLE cms._lps_v_blocks_technology (
    _order integer NOT NULL,
    _parent_id integer NOT NULL,
    _path text NOT NULL,
    _uuid character varying,
    id integer NOT NULL,
    eyebrow character varying,
    heading character varying,
    sub_heading character varying,
    image_upload_id integer,
    image character varying,
    image_alt_text character varying,
    block_name character varying
);



CREATE SEQUENCE cms._lps_v_blocks_technology_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;



ALTER SEQUENCE cms._lps_v_blocks_technology_id_seq OWNED BY cms._lps_v_blocks_technology.id;



CREATE TABLE cms._lps_v_blocks_testimonials_embed (
    _order integer NOT NULL,
    _parent_id integer NOT NULL,
    _path text NOT NULL,
    id integer NOT NULL,
    eyebrow character varying,
    heading character varying,
    "limit" numeric DEFAULT 6,
    filter_by_treatment_id integer,
    filter_by_content_category_id integer,
    _uuid character varying,
    block_name character varying
);



CREATE SEQUENCE cms._lps_v_blocks_testimonials_embed_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;



ALTER SEQUENCE cms._lps_v_blocks_testimonials_embed_id_seq OWNED BY cms._lps_v_blocks_testimonials_embed.id;



CREATE TABLE cms._lps_v_blocks_text_section (
    id integer NOT NULL,
    _parent_id integer NOT NULL,
    _order integer NOT NULL,
    _path text NOT NULL,
    heading character varying,
    content jsonb,
    image character varying,
    image_alt_text character varying,
    _uuid character varying,
    block_name character varying
);



CREATE SEQUENCE cms._lps_v_blocks_text_section_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;



ALTER SEQUENCE cms._lps_v_blocks_text_section_id_seq OWNED BY cms._lps_v_blocks_text_section.id;



CREATE TABLE cms._lps_v_blocks_video_embed (
    id integer NOT NULL,
    _parent_id integer NOT NULL,
    _order integer NOT NULL,
    _path text NOT NULL,
    heading character varying,
    video_url character varying,
    caption character varying,
    _uuid character varying,
    block_name character varying
);



CREATE SEQUENCE cms._lps_v_blocks_video_embed_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;



ALTER SEQUENCE cms._lps_v_blocks_video_embed_id_seq OWNED BY cms._lps_v_blocks_video_embed.id;



CREATE TABLE cms.lps_blocks_before_after_block (
    _order integer NOT NULL,
    _parent_id integer NOT NULL,
    _path text NOT NULL,
    id character varying NOT NULL,
    eyebrow character varying,
    heading character varying,
    block_name character varying
);



CREATE TABLE cms.lps_blocks_before_after_block_items (
    _order integer NOT NULL,
    _parent_id character varying NOT NULL,
    id character varying NOT NULL,
    title character varying,
    before_image_url character varying,
    after_image_url character varying,
    caption character varying
);



CREATE TABLE cms.lps_blocks_benefits_block (
    _order integer NOT NULL,
    _parent_id integer NOT NULL,
    _path text NOT NULL,
    id character varying NOT NULL,
    eyebrow character varying,
    heading character varying,
    block_name character varying
);



CREATE TABLE cms.lps_blocks_benefits_block_items (
    _order integer NOT NULL,
    _parent_id character varying NOT NULL,
    id character varying NOT NULL,
    title character varying,
    description character varying,
    icon cms.enum_lps_blocks_benefits_block_items_icon DEFAULT 'shield'::cms.enum_lps_blocks_benefits_block_items_icon
);



CREATE TABLE cms.lps_blocks_booking_form (
    _order integer NOT NULL,
    _parent_id integer NOT NULL,
    _path text NOT NULL,
    id character varying NOT NULL,
    eyebrow character varying,
    heading character varying DEFAULT 'Book Your Consultation'::character varying,
    cta_label character varying DEFAULT 'Book FREE Consultation'::character varying,
    block_name character varying
);



CREATE TABLE cms.lps_blocks_content_grid (
    _order integer NOT NULL,
    _parent_id integer NOT NULL,
    _path text NOT NULL,
    id character varying NOT NULL,
    eyebrow character varying,
    heading character varying,
    columns cms."gridCols" DEFAULT '2'::cms."gridCols",
    block_name character varying
);



CREATE TABLE cms.lps_blocks_content_grid_items (
    _order integer NOT NULL,
    _parent_id character varying NOT NULL,
    id character varying NOT NULL,
    title character varying,
    description character varying,
    image_url character varying,
    image_alt_text character varying,
    href character varying,
    icon cms.enum_lps_blocks_content_grid_items_icon
);



CREATE TABLE cms.lps_blocks_cta_block (
    _order integer NOT NULL,
    _parent_id integer NOT NULL,
    _path text NOT NULL,
    id character varying NOT NULL,
    heading character varying,
    description character varying,
    primary_cta_label character varying,
    primary_cta_href character varying,
    secondary_cta_label character varying,
    secondary_cta_href character varying,
    variant cms."ctaVariant" DEFAULT 'dark'::cms."ctaVariant",
    block_name character varying
);



CREATE TABLE cms.lps_blocks_data_table (
    _order integer NOT NULL,
    _parent_id integer NOT NULL,
    _path text NOT NULL,
    id character varying NOT NULL,
    eyebrow character varying,
    heading character varying,
    caption character varying,
    block_name character varying
);



CREATE TABLE cms.lps_blocks_data_table_columns (
    _order integer NOT NULL,
    _parent_id character varying NOT NULL,
    id character varying NOT NULL,
    key character varying,
    label character varying,
    align cms.align DEFAULT 'left'::cms.align,
    highlight boolean
);



CREATE TABLE cms.lps_blocks_data_table_rows (
    _order integer NOT NULL,
    _parent_id character varying NOT NULL,
    id character varying NOT NULL
);



CREATE TABLE cms.lps_blocks_data_table_rows_cells (
    _order integer NOT NULL,
    _parent_id character varying NOT NULL,
    id character varying NOT NULL,
    key character varying,
    value character varying
);



CREATE TABLE cms.lps_blocks_doctors_embed (
    _order integer NOT NULL,
    _parent_id integer NOT NULL,
    _path text NOT NULL,
    id character varying NOT NULL,
    eyebrow character varying,
    heading character varying,
    "limit" numeric DEFAULT 6,
    filter_by_content_category_id integer,
    block_name character varying
);



CREATE TABLE cms.lps_blocks_faqs_embed (
    _order integer NOT NULL,
    _parent_id integer NOT NULL,
    _path text NOT NULL,
    id character varying NOT NULL,
    eyebrow character varying,
    heading character varying,
    filter_by_content_category_id integer,
    block_name character varying
);



CREATE TABLE cms.lps_blocks_faqs_embed_inline_faqs (
    _order integer NOT NULL,
    _parent_id character varying NOT NULL,
    id character varying NOT NULL,
    question character varying,
    answer character varying
);



CREATE TABLE cms.lps_blocks_html_embed (
    id character varying NOT NULL,
    _parent_id integer NOT NULL,
    _order integer NOT NULL,
    _path text NOT NULL,
    heading character varying,
    code character varying,
    block_name character varying
);



CREATE SEQUENCE cms.lps_blocks_html_embed_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;



ALTER SEQUENCE cms.lps_blocks_html_embed_id_seq OWNED BY cms.lps_blocks_html_embed.id;



CREATE TABLE cms.lps_blocks_image_slider (
    _order integer NOT NULL,
    _parent_id integer NOT NULL,
    _path text NOT NULL,
    id character varying NOT NULL,
    eyebrow character varying,
    heading character varying,
    aspect_ratio cms."aspectRatio" DEFAULT '16/9'::cms."aspectRatio",
    autoplay_ms numeric DEFAULT 0,
    block_name character varying
);



CREATE TABLE cms.lps_blocks_image_slider_images (
    _order integer NOT NULL,
    _parent_id character varying NOT NULL,
    id character varying NOT NULL,
    image_url character varying,
    image_alt_text character varying,
    caption character varying
);



CREATE TABLE cms.lps_blocks_notice_block (
    _order integer NOT NULL,
    _parent_id integer NOT NULL,
    _path text NOT NULL,
    id character varying NOT NULL,
    variant character varying,
    icon character varying,
    heading character varying,
    body character varying,
    block_name character varying
);



CREATE TABLE cms.lps_blocks_overview_block (
    _order integer NOT NULL,
    _parent_id integer NOT NULL,
    _path text NOT NULL,
    id character varying NOT NULL,
    eyebrow character varying,
    heading character varying,
    block_name character varying
);



CREATE TABLE cms.lps_blocks_overview_block_paragraphs (
    _order integer NOT NULL,
    _parent_id character varying NOT NULL,
    id character varying NOT NULL,
    text character varying
);



CREATE TABLE cms.lps_blocks_pricing_block (
    _order integer NOT NULL,
    _parent_id integer NOT NULL,
    _path text NOT NULL,
    id character varying NOT NULL,
    eyebrow character varying,
    heading character varying,
    block_name character varying
);



CREATE TABLE cms.lps_blocks_pricing_block_plans (
    _order integer NOT NULL,
    _parent_id character varying NOT NULL,
    id character varying NOT NULL,
    name character varying,
    price character varying,
    currency character varying DEFAULT '₹'::character varying,
    description character varying,
    highlighted boolean,
    badge character varying,
    cta_label character varying DEFAULT 'Book Now'::character varying,
    cta_href character varying DEFAULT '#booking'::character varying
);



CREATE TABLE cms.lps_blocks_pricing_block_plans_features (
    _order integer NOT NULL,
    _parent_id character varying NOT NULL,
    id character varying NOT NULL,
    value character varying
);



CREATE TABLE cms.lps_blocks_process_block (
    _order integer NOT NULL,
    _parent_id integer NOT NULL,
    _path text NOT NULL,
    id character varying NOT NULL,
    eyebrow character varying,
    heading character varying,
    block_name character varying
);



CREATE TABLE cms.lps_blocks_process_block_steps (
    _order integer NOT NULL,
    _parent_id character varying NOT NULL,
    id character varying NOT NULL,
    title character varying,
    description character varying
);



CREATE TABLE cms.lps_blocks_stats_block (
    _order integer NOT NULL,
    _parent_id integer NOT NULL,
    _path text NOT NULL,
    id character varying NOT NULL,
    eyebrow character varying,
    heading character varying,
    variant cms."statsVariant" DEFAULT 'dark'::cms."statsVariant",
    block_name character varying
);



CREATE TABLE cms.lps_blocks_stats_block_items (
    _order integer NOT NULL,
    _parent_id character varying NOT NULL,
    id character varying NOT NULL,
    value character varying,
    label character varying,
    suffix character varying
);



CREATE TABLE cms.lps_blocks_takeaways_block (
    _order integer NOT NULL,
    _parent_id integer NOT NULL,
    _path text NOT NULL,
    id character varying NOT NULL,
    heading character varying,
    block_name character varying
);



CREATE TABLE cms.lps_blocks_takeaways_block_items (
    _order integer NOT NULL,
    _parent_id character varying NOT NULL,
    id character varying NOT NULL,
    text character varying
);



CREATE TABLE cms.lps_blocks_technology (
    _order integer NOT NULL,
    _parent_id integer NOT NULL,
    _path text NOT NULL,
    id character varying NOT NULL,
    eyebrow character varying,
    heading character varying,
    sub_heading character varying,
    image_upload_id integer,
    image character varying,
    image_alt_text character varying,
    block_name character varying
);



CREATE TABLE cms.lps_blocks_testimonials_embed (
    _order integer NOT NULL,
    _parent_id integer NOT NULL,
    _path text NOT NULL,
    id character varying NOT NULL,
    eyebrow character varying,
    heading character varying,
    "limit" numeric DEFAULT 6,
    filter_by_treatment_id integer,
    filter_by_content_category_id integer,
    block_name character varying
);



CREATE TABLE cms.lps_blocks_text_section (
    id character varying NOT NULL,
    _parent_id integer NOT NULL,
    _order integer NOT NULL,
    _path text NOT NULL,
    heading character varying,
    content jsonb,
    image character varying,
    image_alt_text character varying,
    block_name character varying
);



CREATE SEQUENCE cms.lps_blocks_text_section_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;



ALTER SEQUENCE cms.lps_blocks_text_section_id_seq OWNED BY cms.lps_blocks_text_section.id;



CREATE TABLE cms.lps_blocks_video_embed (
    id character varying NOT NULL,
    _parent_id integer NOT NULL,
    _order integer NOT NULL,
    _path text NOT NULL,
    heading character varying,
    video_url character varying,
    caption character varying,
    block_name character varying
);



CREATE SEQUENCE cms.lps_blocks_video_embed_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;



ALTER SEQUENCE cms.lps_blocks_video_embed_id_seq OWNED BY cms.lps_blocks_video_embed.id;



ALTER TABLE ONLY cms._lps_v_blocks_before_after_block ALTER COLUMN id SET DEFAULT nextval('cms._lps_v_blocks_before_after_block_id_seq'::regclass);



ALTER TABLE ONLY cms._lps_v_blocks_before_after_block_items ALTER COLUMN id SET DEFAULT nextval('cms._lps_v_blocks_before_after_block_items_id_seq'::regclass);



ALTER TABLE ONLY cms._lps_v_blocks_benefits_block ALTER COLUMN id SET DEFAULT nextval('cms._lps_v_blocks_benefits_block_id_seq'::regclass);



ALTER TABLE ONLY cms._lps_v_blocks_benefits_block_items ALTER COLUMN id SET DEFAULT nextval('cms._lps_v_blocks_benefits_block_items_id_seq'::regclass);



ALTER TABLE ONLY cms._lps_v_blocks_booking_form ALTER COLUMN id SET DEFAULT nextval('cms._lps_v_blocks_booking_form_id_seq'::regclass);



ALTER TABLE ONLY cms._lps_v_blocks_content_grid ALTER COLUMN id SET DEFAULT nextval('cms._lps_v_blocks_content_grid_id_seq'::regclass);



ALTER TABLE ONLY cms._lps_v_blocks_content_grid_items ALTER COLUMN id SET DEFAULT nextval('cms._lps_v_blocks_content_grid_items_id_seq'::regclass);



ALTER TABLE ONLY cms._lps_v_blocks_cta_block ALTER COLUMN id SET DEFAULT nextval('cms._lps_v_blocks_cta_block_id_seq'::regclass);



ALTER TABLE ONLY cms._lps_v_blocks_data_table ALTER COLUMN id SET DEFAULT nextval('cms._lps_v_blocks_data_table_id_seq'::regclass);



ALTER TABLE ONLY cms._lps_v_blocks_data_table_columns ALTER COLUMN id SET DEFAULT nextval('cms._lps_v_blocks_data_table_columns_id_seq'::regclass);



ALTER TABLE ONLY cms._lps_v_blocks_data_table_rows ALTER COLUMN id SET DEFAULT nextval('cms._lps_v_blocks_data_table_rows_id_seq'::regclass);



ALTER TABLE ONLY cms._lps_v_blocks_data_table_rows_cells ALTER COLUMN id SET DEFAULT nextval('cms._lps_v_blocks_data_table_rows_cells_id_seq'::regclass);



ALTER TABLE ONLY cms._lps_v_blocks_doctors_embed ALTER COLUMN id SET DEFAULT nextval('cms._lps_v_blocks_doctors_embed_id_seq'::regclass);



ALTER TABLE ONLY cms._lps_v_blocks_faqs_embed ALTER COLUMN id SET DEFAULT nextval('cms._lps_v_blocks_faqs_embed_id_seq'::regclass);



ALTER TABLE ONLY cms._lps_v_blocks_faqs_embed_inline_faqs ALTER COLUMN id SET DEFAULT nextval('cms._lps_v_blocks_faqs_embed_inline_faqs_id_seq'::regclass);



ALTER TABLE ONLY cms._lps_v_blocks_html_embed ALTER COLUMN id SET DEFAULT nextval('cms._lps_v_blocks_html_embed_id_seq'::regclass);



ALTER TABLE ONLY cms._lps_v_blocks_image_slider ALTER COLUMN id SET DEFAULT nextval('cms._lps_v_blocks_image_slider_id_seq'::regclass);



ALTER TABLE ONLY cms._lps_v_blocks_image_slider_images ALTER COLUMN id SET DEFAULT nextval('cms._lps_v_blocks_image_slider_images_id_seq'::regclass);



ALTER TABLE ONLY cms._lps_v_blocks_notice_block ALTER COLUMN id SET DEFAULT nextval('cms._lps_v_blocks_notice_block_id_seq'::regclass);



ALTER TABLE ONLY cms._lps_v_blocks_overview_block ALTER COLUMN id SET DEFAULT nextval('cms._lps_v_blocks_overview_block_id_seq'::regclass);



ALTER TABLE ONLY cms._lps_v_blocks_overview_block_paragraphs ALTER COLUMN id SET DEFAULT nextval('cms._lps_v_blocks_overview_block_paragraphs_id_seq'::regclass);



ALTER TABLE ONLY cms._lps_v_blocks_pricing_block ALTER COLUMN id SET DEFAULT nextval('cms._lps_v_blocks_pricing_block_id_seq'::regclass);



ALTER TABLE ONLY cms._lps_v_blocks_pricing_block_plans ALTER COLUMN id SET DEFAULT nextval('cms._lps_v_blocks_pricing_block_plans_id_seq'::regclass);



ALTER TABLE ONLY cms._lps_v_blocks_pricing_block_plans_features ALTER COLUMN id SET DEFAULT nextval('cms._lps_v_blocks_pricing_block_plans_features_id_seq'::regclass);



ALTER TABLE ONLY cms._lps_v_blocks_process_block ALTER COLUMN id SET DEFAULT nextval('cms._lps_v_blocks_process_block_id_seq'::regclass);



ALTER TABLE ONLY cms._lps_v_blocks_process_block_steps ALTER COLUMN id SET DEFAULT nextval('cms._lps_v_blocks_process_block_steps_id_seq'::regclass);



ALTER TABLE ONLY cms._lps_v_blocks_stats_block ALTER COLUMN id SET DEFAULT nextval('cms._lps_v_blocks_stats_block_id_seq'::regclass);



ALTER TABLE ONLY cms._lps_v_blocks_stats_block_items ALTER COLUMN id SET DEFAULT nextval('cms._lps_v_blocks_stats_block_items_id_seq'::regclass);



ALTER TABLE ONLY cms._lps_v_blocks_takeaways_block ALTER COLUMN id SET DEFAULT nextval('cms._lps_v_blocks_takeaways_block_id_seq'::regclass);



ALTER TABLE ONLY cms._lps_v_blocks_takeaways_block_items ALTER COLUMN id SET DEFAULT nextval('cms._lps_v_blocks_takeaways_block_items_id_seq'::regclass);



ALTER TABLE ONLY cms._lps_v_blocks_technology ALTER COLUMN id SET DEFAULT nextval('cms._lps_v_blocks_technology_id_seq'::regclass);



ALTER TABLE ONLY cms._lps_v_blocks_testimonials_embed ALTER COLUMN id SET DEFAULT nextval('cms._lps_v_blocks_testimonials_embed_id_seq'::regclass);



ALTER TABLE ONLY cms._lps_v_blocks_text_section ALTER COLUMN id SET DEFAULT nextval('cms._lps_v_blocks_text_section_id_seq'::regclass);



ALTER TABLE ONLY cms._lps_v_blocks_video_embed ALTER COLUMN id SET DEFAULT nextval('cms._lps_v_blocks_video_embed_id_seq'::regclass);



ALTER TABLE ONLY cms._lps_v_blocks_before_after_block_items
    ADD CONSTRAINT _lps_v_blocks_before_after_block_items_pkey PRIMARY KEY (id);



ALTER TABLE ONLY cms._lps_v_blocks_before_after_block
    ADD CONSTRAINT _lps_v_blocks_before_after_block_pkey PRIMARY KEY (id);



ALTER TABLE ONLY cms._lps_v_blocks_benefits_block_items
    ADD CONSTRAINT _lps_v_blocks_benefits_block_items_pkey PRIMARY KEY (id);



ALTER TABLE ONLY cms._lps_v_blocks_benefits_block
    ADD CONSTRAINT _lps_v_blocks_benefits_block_pkey PRIMARY KEY (id);



ALTER TABLE ONLY cms._lps_v_blocks_booking_form
    ADD CONSTRAINT _lps_v_blocks_booking_form_pkey PRIMARY KEY (id);



ALTER TABLE ONLY cms._lps_v_blocks_content_grid_items
    ADD CONSTRAINT _lps_v_blocks_content_grid_items_pkey PRIMARY KEY (id);



ALTER TABLE ONLY cms._lps_v_blocks_content_grid
    ADD CONSTRAINT _lps_v_blocks_content_grid_pkey PRIMARY KEY (id);



ALTER TABLE ONLY cms._lps_v_blocks_cta_block
    ADD CONSTRAINT _lps_v_blocks_cta_block_pkey PRIMARY KEY (id);



ALTER TABLE ONLY cms._lps_v_blocks_data_table_columns
    ADD CONSTRAINT _lps_v_blocks_data_table_columns_pkey PRIMARY KEY (id);



ALTER TABLE ONLY cms._lps_v_blocks_data_table
    ADD CONSTRAINT _lps_v_blocks_data_table_pkey PRIMARY KEY (id);



ALTER TABLE ONLY cms._lps_v_blocks_data_table_rows_cells
    ADD CONSTRAINT _lps_v_blocks_data_table_rows_cells_pkey PRIMARY KEY (id);



ALTER TABLE ONLY cms._lps_v_blocks_data_table_rows
    ADD CONSTRAINT _lps_v_blocks_data_table_rows_pkey PRIMARY KEY (id);



ALTER TABLE ONLY cms._lps_v_blocks_doctors_embed
    ADD CONSTRAINT _lps_v_blocks_doctors_embed_pkey PRIMARY KEY (id);



ALTER TABLE ONLY cms._lps_v_blocks_faqs_embed_inline_faqs
    ADD CONSTRAINT _lps_v_blocks_faqs_embed_inline_faqs_pkey PRIMARY KEY (id);



ALTER TABLE ONLY cms._lps_v_blocks_faqs_embed
    ADD CONSTRAINT _lps_v_blocks_faqs_embed_pkey PRIMARY KEY (id);



ALTER TABLE ONLY cms._lps_v_blocks_html_embed
    ADD CONSTRAINT _lps_v_blocks_html_embed_pkey PRIMARY KEY (id);



ALTER TABLE ONLY cms._lps_v_blocks_image_slider_images
    ADD CONSTRAINT _lps_v_blocks_image_slider_images_pkey PRIMARY KEY (id);



ALTER TABLE ONLY cms._lps_v_blocks_image_slider
    ADD CONSTRAINT _lps_v_blocks_image_slider_pkey PRIMARY KEY (id);



ALTER TABLE ONLY cms._lps_v_blocks_notice_block
    ADD CONSTRAINT _lps_v_blocks_notice_block_pkey PRIMARY KEY (id);



ALTER TABLE ONLY cms._lps_v_blocks_overview_block_paragraphs
    ADD CONSTRAINT _lps_v_blocks_overview_block_paragraphs_pkey PRIMARY KEY (id);



ALTER TABLE ONLY cms._lps_v_blocks_overview_block
    ADD CONSTRAINT _lps_v_blocks_overview_block_pkey PRIMARY KEY (id);



ALTER TABLE ONLY cms._lps_v_blocks_pricing_block
    ADD CONSTRAINT _lps_v_blocks_pricing_block_pkey PRIMARY KEY (id);



ALTER TABLE ONLY cms._lps_v_blocks_pricing_block_plans_features
    ADD CONSTRAINT _lps_v_blocks_pricing_block_plans_features_pkey PRIMARY KEY (id);



ALTER TABLE ONLY cms._lps_v_blocks_pricing_block_plans
    ADD CONSTRAINT _lps_v_blocks_pricing_block_plans_pkey PRIMARY KEY (id);



ALTER TABLE ONLY cms._lps_v_blocks_process_block
    ADD CONSTRAINT _lps_v_blocks_process_block_pkey PRIMARY KEY (id);



ALTER TABLE ONLY cms._lps_v_blocks_process_block_steps
    ADD CONSTRAINT _lps_v_blocks_process_block_steps_pkey PRIMARY KEY (id);



ALTER TABLE ONLY cms._lps_v_blocks_stats_block_items
    ADD CONSTRAINT _lps_v_blocks_stats_block_items_pkey PRIMARY KEY (id);



ALTER TABLE ONLY cms._lps_v_blocks_stats_block
    ADD CONSTRAINT _lps_v_blocks_stats_block_pkey PRIMARY KEY (id);



ALTER TABLE ONLY cms._lps_v_blocks_takeaways_block_items
    ADD CONSTRAINT _lps_v_blocks_takeaways_block_items_pkey PRIMARY KEY (id);



ALTER TABLE ONLY cms._lps_v_blocks_takeaways_block
    ADD CONSTRAINT _lps_v_blocks_takeaways_block_pkey PRIMARY KEY (id);



ALTER TABLE ONLY cms._lps_v_blocks_technology
    ADD CONSTRAINT _lps_v_blocks_technology_pkey PRIMARY KEY (id);



ALTER TABLE ONLY cms._lps_v_blocks_testimonials_embed
    ADD CONSTRAINT _lps_v_blocks_testimonials_embed_pkey PRIMARY KEY (id);



ALTER TABLE ONLY cms._lps_v_blocks_text_section
    ADD CONSTRAINT _lps_v_blocks_text_section_pkey PRIMARY KEY (id);



ALTER TABLE ONLY cms._lps_v_blocks_video_embed
    ADD CONSTRAINT _lps_v_blocks_video_embed_pkey PRIMARY KEY (id);



ALTER TABLE ONLY cms.lps_blocks_before_after_block_items
    ADD CONSTRAINT lps_blocks_before_after_block_items_pkey PRIMARY KEY (id);



ALTER TABLE ONLY cms.lps_blocks_before_after_block
    ADD CONSTRAINT lps_blocks_before_after_block_pkey PRIMARY KEY (id);



ALTER TABLE ONLY cms.lps_blocks_benefits_block_items
    ADD CONSTRAINT lps_blocks_benefits_block_items_pkey PRIMARY KEY (id);



ALTER TABLE ONLY cms.lps_blocks_benefits_block
    ADD CONSTRAINT lps_blocks_benefits_block_pkey PRIMARY KEY (id);



ALTER TABLE ONLY cms.lps_blocks_booking_form
    ADD CONSTRAINT lps_blocks_booking_form_pkey PRIMARY KEY (id);



ALTER TABLE ONLY cms.lps_blocks_content_grid_items
    ADD CONSTRAINT lps_blocks_content_grid_items_pkey PRIMARY KEY (id);



ALTER TABLE ONLY cms.lps_blocks_content_grid
    ADD CONSTRAINT lps_blocks_content_grid_pkey PRIMARY KEY (id);



ALTER TABLE ONLY cms.lps_blocks_cta_block
    ADD CONSTRAINT lps_blocks_cta_block_pkey PRIMARY KEY (id);



ALTER TABLE ONLY cms.lps_blocks_data_table_columns
    ADD CONSTRAINT lps_blocks_data_table_columns_pkey PRIMARY KEY (id);



ALTER TABLE ONLY cms.lps_blocks_data_table
    ADD CONSTRAINT lps_blocks_data_table_pkey PRIMARY KEY (id);



ALTER TABLE ONLY cms.lps_blocks_data_table_rows_cells
    ADD CONSTRAINT lps_blocks_data_table_rows_cells_pkey PRIMARY KEY (id);



ALTER TABLE ONLY cms.lps_blocks_data_table_rows
    ADD CONSTRAINT lps_blocks_data_table_rows_pkey PRIMARY KEY (id);



ALTER TABLE ONLY cms.lps_blocks_doctors_embed
    ADD CONSTRAINT lps_blocks_doctors_embed_pkey PRIMARY KEY (id);



ALTER TABLE ONLY cms.lps_blocks_faqs_embed_inline_faqs
    ADD CONSTRAINT lps_blocks_faqs_embed_inline_faqs_pkey PRIMARY KEY (id);



ALTER TABLE ONLY cms.lps_blocks_faqs_embed
    ADD CONSTRAINT lps_blocks_faqs_embed_pkey PRIMARY KEY (id);



ALTER TABLE ONLY cms.lps_blocks_html_embed
    ADD CONSTRAINT lps_blocks_html_embed_pkey PRIMARY KEY (id);



ALTER TABLE ONLY cms.lps_blocks_image_slider_images
    ADD CONSTRAINT lps_blocks_image_slider_images_pkey PRIMARY KEY (id);



ALTER TABLE ONLY cms.lps_blocks_image_slider
    ADD CONSTRAINT lps_blocks_image_slider_pkey PRIMARY KEY (id);



ALTER TABLE ONLY cms.lps_blocks_notice_block
    ADD CONSTRAINT lps_blocks_notice_block_pkey PRIMARY KEY (id);



ALTER TABLE ONLY cms.lps_blocks_overview_block_paragraphs
    ADD CONSTRAINT lps_blocks_overview_block_paragraphs_pkey PRIMARY KEY (id);



ALTER TABLE ONLY cms.lps_blocks_overview_block
    ADD CONSTRAINT lps_blocks_overview_block_pkey PRIMARY KEY (id);



ALTER TABLE ONLY cms.lps_blocks_pricing_block
    ADD CONSTRAINT lps_blocks_pricing_block_pkey PRIMARY KEY (id);



ALTER TABLE ONLY cms.lps_blocks_pricing_block_plans_features
    ADD CONSTRAINT lps_blocks_pricing_block_plans_features_pkey PRIMARY KEY (id);



ALTER TABLE ONLY cms.lps_blocks_pricing_block_plans
    ADD CONSTRAINT lps_blocks_pricing_block_plans_pkey PRIMARY KEY (id);



ALTER TABLE ONLY cms.lps_blocks_process_block
    ADD CONSTRAINT lps_blocks_process_block_pkey PRIMARY KEY (id);



ALTER TABLE ONLY cms.lps_blocks_process_block_steps
    ADD CONSTRAINT lps_blocks_process_block_steps_pkey PRIMARY KEY (id);



ALTER TABLE ONLY cms.lps_blocks_stats_block_items
    ADD CONSTRAINT lps_blocks_stats_block_items_pkey PRIMARY KEY (id);



ALTER TABLE ONLY cms.lps_blocks_stats_block
    ADD CONSTRAINT lps_blocks_stats_block_pkey PRIMARY KEY (id);



ALTER TABLE ONLY cms.lps_blocks_takeaways_block_items
    ADD CONSTRAINT lps_blocks_takeaways_block_items_pkey PRIMARY KEY (id);



ALTER TABLE ONLY cms.lps_blocks_takeaways_block
    ADD CONSTRAINT lps_blocks_takeaways_block_pkey PRIMARY KEY (id);



ALTER TABLE ONLY cms.lps_blocks_technology
    ADD CONSTRAINT lps_blocks_technology_pkey PRIMARY KEY (id);



ALTER TABLE ONLY cms.lps_blocks_testimonials_embed
    ADD CONSTRAINT lps_blocks_testimonials_embed_pkey PRIMARY KEY (id);



ALTER TABLE ONLY cms.lps_blocks_text_section
    ADD CONSTRAINT lps_blocks_text_section_pkey PRIMARY KEY (id);



ALTER TABLE ONLY cms.lps_blocks_video_embed
    ADD CONSTRAINT lps_blocks_video_embed_pkey PRIMARY KEY (id);



CREATE INDEX _lps_v_blocks_before_after_block_items_order_idx ON cms._lps_v_blocks_before_after_block_items USING btree (_order);



CREATE INDEX _lps_v_blocks_before_after_block_items_parent_id_idx ON cms._lps_v_blocks_before_after_block_items USING btree (_parent_id);



CREATE INDEX _lps_v_blocks_before_after_block_order_idx ON cms._lps_v_blocks_before_after_block USING btree (_order);



CREATE INDEX _lps_v_blocks_before_after_block_parent_id_idx ON cms._lps_v_blocks_before_after_block USING btree (_parent_id);



CREATE INDEX _lps_v_blocks_before_after_block_path_idx ON cms._lps_v_blocks_before_after_block USING btree (_path);



CREATE INDEX _lps_v_blocks_benefits_block_items_order_idx ON cms._lps_v_blocks_benefits_block_items USING btree (_order);



CREATE INDEX _lps_v_blocks_benefits_block_items_parent_id_idx ON cms._lps_v_blocks_benefits_block_items USING btree (_parent_id);



CREATE INDEX _lps_v_blocks_benefits_block_order_idx ON cms._lps_v_blocks_benefits_block USING btree (_order);



CREATE INDEX _lps_v_blocks_benefits_block_parent_id_idx ON cms._lps_v_blocks_benefits_block USING btree (_parent_id);



CREATE INDEX _lps_v_blocks_benefits_block_path_idx ON cms._lps_v_blocks_benefits_block USING btree (_path);



CREATE INDEX _lps_v_blocks_booking_form_order_idx ON cms._lps_v_blocks_booking_form USING btree (_order);



CREATE INDEX _lps_v_blocks_booking_form_parent_id_idx ON cms._lps_v_blocks_booking_form USING btree (_parent_id);



CREATE INDEX _lps_v_blocks_booking_form_path_idx ON cms._lps_v_blocks_booking_form USING btree (_path);



CREATE INDEX _lps_v_blocks_content_grid_items_order_idx ON cms._lps_v_blocks_content_grid_items USING btree (_order);



CREATE INDEX _lps_v_blocks_content_grid_items_parent_id_idx ON cms._lps_v_blocks_content_grid_items USING btree (_parent_id);



CREATE INDEX _lps_v_blocks_content_grid_order_idx ON cms._lps_v_blocks_content_grid USING btree (_order);



CREATE INDEX _lps_v_blocks_content_grid_parent_id_idx ON cms._lps_v_blocks_content_grid USING btree (_parent_id);



CREATE INDEX _lps_v_blocks_content_grid_path_idx ON cms._lps_v_blocks_content_grid USING btree (_path);



CREATE INDEX _lps_v_blocks_cta_block_order_idx ON cms._lps_v_blocks_cta_block USING btree (_order);



CREATE INDEX _lps_v_blocks_cta_block_parent_id_idx ON cms._lps_v_blocks_cta_block USING btree (_parent_id);



CREATE INDEX _lps_v_blocks_cta_block_path_idx ON cms._lps_v_blocks_cta_block USING btree (_path);



CREATE INDEX _lps_v_blocks_data_table_columns_order_idx ON cms._lps_v_blocks_data_table_columns USING btree (_order);



CREATE INDEX _lps_v_blocks_data_table_columns_parent_id_idx ON cms._lps_v_blocks_data_table_columns USING btree (_parent_id);



CREATE INDEX _lps_v_blocks_data_table_order_idx ON cms._lps_v_blocks_data_table USING btree (_order);



CREATE INDEX _lps_v_blocks_data_table_parent_id_idx ON cms._lps_v_blocks_data_table USING btree (_parent_id);



CREATE INDEX _lps_v_blocks_data_table_path_idx ON cms._lps_v_blocks_data_table USING btree (_path);



CREATE INDEX _lps_v_blocks_data_table_rows_cells_order_idx ON cms._lps_v_blocks_data_table_rows_cells USING btree (_order);



CREATE INDEX _lps_v_blocks_data_table_rows_cells_parent_id_idx ON cms._lps_v_blocks_data_table_rows_cells USING btree (_parent_id);



CREATE INDEX _lps_v_blocks_data_table_rows_order_idx ON cms._lps_v_blocks_data_table_rows USING btree (_order);



CREATE INDEX _lps_v_blocks_data_table_rows_parent_id_idx ON cms._lps_v_blocks_data_table_rows USING btree (_parent_id);



CREATE INDEX _lps_v_blocks_doctors_embed_filter_by_content_categ_idx ON cms._lps_v_blocks_doctors_embed USING btree (filter_by_content_category_id);



CREATE INDEX _lps_v_blocks_doctors_embed_order_idx ON cms._lps_v_blocks_doctors_embed USING btree (_order);



CREATE INDEX _lps_v_blocks_doctors_embed_parent_id_idx ON cms._lps_v_blocks_doctors_embed USING btree (_parent_id);



CREATE INDEX _lps_v_blocks_doctors_embed_path_idx ON cms._lps_v_blocks_doctors_embed USING btree (_path);



CREATE INDEX _lps_v_blocks_faqs_embed_filter_by_content_category_idx ON cms._lps_v_blocks_faqs_embed USING btree (filter_by_content_category_id);



CREATE INDEX _lps_v_blocks_faqs_embed_inline_faqs_order_idx ON cms._lps_v_blocks_faqs_embed_inline_faqs USING btree (_order);



CREATE INDEX _lps_v_blocks_faqs_embed_inline_faqs_parent_id_idx ON cms._lps_v_blocks_faqs_embed_inline_faqs USING btree (_parent_id);



CREATE INDEX _lps_v_blocks_faqs_embed_order_idx ON cms._lps_v_blocks_faqs_embed USING btree (_order);



CREATE INDEX _lps_v_blocks_faqs_embed_parent_id_idx ON cms._lps_v_blocks_faqs_embed USING btree (_parent_id);



CREATE INDEX _lps_v_blocks_faqs_embed_path_idx ON cms._lps_v_blocks_faqs_embed USING btree (_path);



CREATE INDEX _lps_v_blocks_html_embed_order_idx ON cms._lps_v_blocks_html_embed USING btree (_order);



CREATE INDEX _lps_v_blocks_html_embed_parent_id_idx ON cms._lps_v_blocks_html_embed USING btree (_parent_id);



CREATE INDEX _lps_v_blocks_html_embed_path_idx ON cms._lps_v_blocks_html_embed USING btree (_path);



CREATE INDEX _lps_v_blocks_image_slider_images_order_idx ON cms._lps_v_blocks_image_slider_images USING btree (_order);



CREATE INDEX _lps_v_blocks_image_slider_images_parent_id_idx ON cms._lps_v_blocks_image_slider_images USING btree (_parent_id);



CREATE INDEX _lps_v_blocks_image_slider_order_idx ON cms._lps_v_blocks_image_slider USING btree (_order);



CREATE INDEX _lps_v_blocks_image_slider_parent_id_idx ON cms._lps_v_blocks_image_slider USING btree (_parent_id);



CREATE INDEX _lps_v_blocks_image_slider_path_idx ON cms._lps_v_blocks_image_slider USING btree (_path);



CREATE INDEX _lps_v_blocks_notice_block_order_idx ON cms._lps_v_blocks_notice_block USING btree (_order);



CREATE INDEX _lps_v_blocks_notice_block_parent_id_idx ON cms._lps_v_blocks_notice_block USING btree (_parent_id);



CREATE INDEX _lps_v_blocks_notice_block_path_idx ON cms._lps_v_blocks_notice_block USING btree (_path);



CREATE INDEX _lps_v_blocks_overview_block_order_idx ON cms._lps_v_blocks_overview_block USING btree (_order);



CREATE INDEX _lps_v_blocks_overview_block_paragraphs_order_idx ON cms._lps_v_blocks_overview_block_paragraphs USING btree (_order);



CREATE INDEX _lps_v_blocks_overview_block_paragraphs_parent_id_idx ON cms._lps_v_blocks_overview_block_paragraphs USING btree (_parent_id);



CREATE INDEX _lps_v_blocks_overview_block_parent_id_idx ON cms._lps_v_blocks_overview_block USING btree (_parent_id);



CREATE INDEX _lps_v_blocks_overview_block_path_idx ON cms._lps_v_blocks_overview_block USING btree (_path);



CREATE INDEX _lps_v_blocks_pricing_block_order_idx ON cms._lps_v_blocks_pricing_block USING btree (_order);



CREATE INDEX _lps_v_blocks_pricing_block_parent_id_idx ON cms._lps_v_blocks_pricing_block USING btree (_parent_id);



CREATE INDEX _lps_v_blocks_pricing_block_path_idx ON cms._lps_v_blocks_pricing_block USING btree (_path);



CREATE INDEX _lps_v_blocks_pricing_block_plans_features_order_idx ON cms._lps_v_blocks_pricing_block_plans_features USING btree (_order);



CREATE INDEX _lps_v_blocks_pricing_block_plans_features_parent_id_idx ON cms._lps_v_blocks_pricing_block_plans_features USING btree (_parent_id);



CREATE INDEX _lps_v_blocks_pricing_block_plans_order_idx ON cms._lps_v_blocks_pricing_block_plans USING btree (_order);



CREATE INDEX _lps_v_blocks_pricing_block_plans_parent_id_idx ON cms._lps_v_blocks_pricing_block_plans USING btree (_parent_id);



CREATE INDEX _lps_v_blocks_process_block_order_idx ON cms._lps_v_blocks_process_block USING btree (_order);



CREATE INDEX _lps_v_blocks_process_block_parent_id_idx ON cms._lps_v_blocks_process_block USING btree (_parent_id);



CREATE INDEX _lps_v_blocks_process_block_path_idx ON cms._lps_v_blocks_process_block USING btree (_path);



CREATE INDEX _lps_v_blocks_process_block_steps_order_idx ON cms._lps_v_blocks_process_block_steps USING btree (_order);



CREATE INDEX _lps_v_blocks_process_block_steps_parent_id_idx ON cms._lps_v_blocks_process_block_steps USING btree (_parent_id);



CREATE INDEX _lps_v_blocks_stats_block_items_order_idx ON cms._lps_v_blocks_stats_block_items USING btree (_order);



CREATE INDEX _lps_v_blocks_stats_block_items_parent_id_idx ON cms._lps_v_blocks_stats_block_items USING btree (_parent_id);



CREATE INDEX _lps_v_blocks_stats_block_order_idx ON cms._lps_v_blocks_stats_block USING btree (_order);



CREATE INDEX _lps_v_blocks_stats_block_parent_id_idx ON cms._lps_v_blocks_stats_block USING btree (_parent_id);



CREATE INDEX _lps_v_blocks_stats_block_path_idx ON cms._lps_v_blocks_stats_block USING btree (_path);



CREATE INDEX _lps_v_blocks_takeaways_block_items_order_idx ON cms._lps_v_blocks_takeaways_block_items USING btree (_order);



CREATE INDEX _lps_v_blocks_takeaways_block_items_parent_id_idx ON cms._lps_v_blocks_takeaways_block_items USING btree (_parent_id);



CREATE INDEX _lps_v_blocks_takeaways_block_order_idx ON cms._lps_v_blocks_takeaways_block USING btree (_order);



CREATE INDEX _lps_v_blocks_takeaways_block_parent_id_idx ON cms._lps_v_blocks_takeaways_block USING btree (_parent_id);



CREATE INDEX _lps_v_blocks_takeaways_block_path_idx ON cms._lps_v_blocks_takeaways_block USING btree (_path);



CREATE INDEX _lps_v_blocks_technology_order_idx ON cms._lps_v_blocks_technology USING btree (_order);



CREATE INDEX _lps_v_blocks_technology_parent_id_idx ON cms._lps_v_blocks_technology USING btree (_parent_id);



CREATE INDEX _lps_v_blocks_technology_path_idx ON cms._lps_v_blocks_technology USING btree (_path);



CREATE INDEX _lps_v_blocks_testimonials_embed_filter_by_content__idx ON cms._lps_v_blocks_testimonials_embed USING btree (filter_by_content_category_id);



CREATE INDEX _lps_v_blocks_testimonials_embed_filter_by_treatmen_idx ON cms._lps_v_blocks_testimonials_embed USING btree (filter_by_treatment_id);



CREATE INDEX _lps_v_blocks_testimonials_embed_order_idx ON cms._lps_v_blocks_testimonials_embed USING btree (_order);



CREATE INDEX _lps_v_blocks_testimonials_embed_parent_id_idx ON cms._lps_v_blocks_testimonials_embed USING btree (_parent_id);



CREATE INDEX _lps_v_blocks_testimonials_embed_path_idx ON cms._lps_v_blocks_testimonials_embed USING btree (_path);



CREATE INDEX _lps_v_blocks_text_section_order_idx ON cms._lps_v_blocks_text_section USING btree (_order);



CREATE INDEX _lps_v_blocks_text_section_parent_id_idx ON cms._lps_v_blocks_text_section USING btree (_parent_id);



CREATE INDEX _lps_v_blocks_text_section_path_idx ON cms._lps_v_blocks_text_section USING btree (_path);



CREATE INDEX _lps_v_blocks_video_embed_order_idx ON cms._lps_v_blocks_video_embed USING btree (_order);



CREATE INDEX _lps_v_blocks_video_embed_parent_id_idx ON cms._lps_v_blocks_video_embed USING btree (_parent_id);



CREATE INDEX _lps_v_blocks_video_embed_path_idx ON cms._lps_v_blocks_video_embed USING btree (_path);



CREATE INDEX lps_blocks_before_after_block_items_order_idx ON cms.lps_blocks_before_after_block_items USING btree (_order);



CREATE INDEX lps_blocks_before_after_block_items_parent_id_idx ON cms.lps_blocks_before_after_block_items USING btree (_parent_id);



CREATE INDEX lps_blocks_before_after_block_order_idx ON cms.lps_blocks_before_after_block USING btree (_order);



CREATE INDEX lps_blocks_before_after_block_parent_id_idx ON cms.lps_blocks_before_after_block USING btree (_parent_id);



CREATE INDEX lps_blocks_before_after_block_path_idx ON cms.lps_blocks_before_after_block USING btree (_path);



CREATE INDEX lps_blocks_benefits_block_items_order_idx ON cms.lps_blocks_benefits_block_items USING btree (_order);



CREATE INDEX lps_blocks_benefits_block_items_parent_id_idx ON cms.lps_blocks_benefits_block_items USING btree (_parent_id);



CREATE INDEX lps_blocks_benefits_block_order_idx ON cms.lps_blocks_benefits_block USING btree (_order);



CREATE INDEX lps_blocks_benefits_block_parent_id_idx ON cms.lps_blocks_benefits_block USING btree (_parent_id);



CREATE INDEX lps_blocks_benefits_block_path_idx ON cms.lps_blocks_benefits_block USING btree (_path);



CREATE INDEX lps_blocks_booking_form_order_idx ON cms.lps_blocks_booking_form USING btree (_order);



CREATE INDEX lps_blocks_booking_form_parent_id_idx ON cms.lps_blocks_booking_form USING btree (_parent_id);



CREATE INDEX lps_blocks_booking_form_path_idx ON cms.lps_blocks_booking_form USING btree (_path);



CREATE INDEX lps_blocks_content_grid_items_order_idx ON cms.lps_blocks_content_grid_items USING btree (_order);



CREATE INDEX lps_blocks_content_grid_items_parent_id_idx ON cms.lps_blocks_content_grid_items USING btree (_parent_id);



CREATE INDEX lps_blocks_content_grid_order_idx ON cms.lps_blocks_content_grid USING btree (_order);



CREATE INDEX lps_blocks_content_grid_parent_id_idx ON cms.lps_blocks_content_grid USING btree (_parent_id);



CREATE INDEX lps_blocks_content_grid_path_idx ON cms.lps_blocks_content_grid USING btree (_path);



CREATE INDEX lps_blocks_cta_block_order_idx ON cms.lps_blocks_cta_block USING btree (_order);



CREATE INDEX lps_blocks_cta_block_parent_id_idx ON cms.lps_blocks_cta_block USING btree (_parent_id);



CREATE INDEX lps_blocks_cta_block_path_idx ON cms.lps_blocks_cta_block USING btree (_path);



CREATE INDEX lps_blocks_data_table_columns_order_idx ON cms.lps_blocks_data_table_columns USING btree (_order);



CREATE INDEX lps_blocks_data_table_columns_parent_id_idx ON cms.lps_blocks_data_table_columns USING btree (_parent_id);



CREATE INDEX lps_blocks_data_table_order_idx ON cms.lps_blocks_data_table USING btree (_order);



CREATE INDEX lps_blocks_data_table_parent_id_idx ON cms.lps_blocks_data_table USING btree (_parent_id);



CREATE INDEX lps_blocks_data_table_path_idx ON cms.lps_blocks_data_table USING btree (_path);



CREATE INDEX lps_blocks_data_table_rows_cells_order_idx ON cms.lps_blocks_data_table_rows_cells USING btree (_order);



CREATE INDEX lps_blocks_data_table_rows_cells_parent_id_idx ON cms.lps_blocks_data_table_rows_cells USING btree (_parent_id);



CREATE INDEX lps_blocks_data_table_rows_order_idx ON cms.lps_blocks_data_table_rows USING btree (_order);



CREATE INDEX lps_blocks_data_table_rows_parent_id_idx ON cms.lps_blocks_data_table_rows USING btree (_parent_id);



CREATE INDEX lps_blocks_doctors_embed_filter_by_content_category_idx ON cms.lps_blocks_doctors_embed USING btree (filter_by_content_category_id);



CREATE INDEX lps_blocks_doctors_embed_order_idx ON cms.lps_blocks_doctors_embed USING btree (_order);



CREATE INDEX lps_blocks_doctors_embed_parent_id_idx ON cms.lps_blocks_doctors_embed USING btree (_parent_id);



CREATE INDEX lps_blocks_doctors_embed_path_idx ON cms.lps_blocks_doctors_embed USING btree (_path);



CREATE INDEX lps_blocks_faqs_embed_filter_by_content_category_idx ON cms.lps_blocks_faqs_embed USING btree (filter_by_content_category_id);



CREATE INDEX lps_blocks_faqs_embed_inline_faqs_order_idx ON cms.lps_blocks_faqs_embed_inline_faqs USING btree (_order);



CREATE INDEX lps_blocks_faqs_embed_inline_faqs_parent_id_idx ON cms.lps_blocks_faqs_embed_inline_faqs USING btree (_parent_id);



CREATE INDEX lps_blocks_faqs_embed_order_idx ON cms.lps_blocks_faqs_embed USING btree (_order);



CREATE INDEX lps_blocks_faqs_embed_parent_id_idx ON cms.lps_blocks_faqs_embed USING btree (_parent_id);



CREATE INDEX lps_blocks_faqs_embed_path_idx ON cms.lps_blocks_faqs_embed USING btree (_path);



CREATE INDEX lps_blocks_html_embed_order_idx ON cms.lps_blocks_html_embed USING btree (_order);



CREATE INDEX lps_blocks_html_embed_parent_id_idx ON cms.lps_blocks_html_embed USING btree (_parent_id);



CREATE INDEX lps_blocks_html_embed_path_idx ON cms.lps_blocks_html_embed USING btree (_path);



CREATE INDEX lps_blocks_image_slider_images_order_idx ON cms.lps_blocks_image_slider_images USING btree (_order);



CREATE INDEX lps_blocks_image_slider_images_parent_id_idx ON cms.lps_blocks_image_slider_images USING btree (_parent_id);



CREATE INDEX lps_blocks_image_slider_order_idx ON cms.lps_blocks_image_slider USING btree (_order);



CREATE INDEX lps_blocks_image_slider_parent_id_idx ON cms.lps_blocks_image_slider USING btree (_parent_id);



CREATE INDEX lps_blocks_image_slider_path_idx ON cms.lps_blocks_image_slider USING btree (_path);



CREATE INDEX lps_blocks_notice_block_order_idx ON cms.lps_blocks_notice_block USING btree (_order);



CREATE INDEX lps_blocks_notice_block_parent_id_idx ON cms.lps_blocks_notice_block USING btree (_parent_id);



CREATE INDEX lps_blocks_notice_block_path_idx ON cms.lps_blocks_notice_block USING btree (_path);



CREATE INDEX lps_blocks_overview_block_order_idx ON cms.lps_blocks_overview_block USING btree (_order);



CREATE INDEX lps_blocks_overview_block_paragraphs_order_idx ON cms.lps_blocks_overview_block_paragraphs USING btree (_order);



CREATE INDEX lps_blocks_overview_block_paragraphs_parent_id_idx ON cms.lps_blocks_overview_block_paragraphs USING btree (_parent_id);



CREATE INDEX lps_blocks_overview_block_parent_id_idx ON cms.lps_blocks_overview_block USING btree (_parent_id);



CREATE INDEX lps_blocks_overview_block_path_idx ON cms.lps_blocks_overview_block USING btree (_path);



CREATE INDEX lps_blocks_pricing_block_order_idx ON cms.lps_blocks_pricing_block USING btree (_order);



CREATE INDEX lps_blocks_pricing_block_parent_id_idx ON cms.lps_blocks_pricing_block USING btree (_parent_id);



CREATE INDEX lps_blocks_pricing_block_path_idx ON cms.lps_blocks_pricing_block USING btree (_path);



CREATE INDEX lps_blocks_pricing_block_plans_features_order_idx ON cms.lps_blocks_pricing_block_plans_features USING btree (_order);



CREATE INDEX lps_blocks_pricing_block_plans_features_parent_id_idx ON cms.lps_blocks_pricing_block_plans_features USING btree (_parent_id);



CREATE INDEX lps_blocks_pricing_block_plans_order_idx ON cms.lps_blocks_pricing_block_plans USING btree (_order);



CREATE INDEX lps_blocks_pricing_block_plans_parent_id_idx ON cms.lps_blocks_pricing_block_plans USING btree (_parent_id);



CREATE INDEX lps_blocks_process_block_order_idx ON cms.lps_blocks_process_block USING btree (_order);



CREATE INDEX lps_blocks_process_block_parent_id_idx ON cms.lps_blocks_process_block USING btree (_parent_id);



CREATE INDEX lps_blocks_process_block_path_idx ON cms.lps_blocks_process_block USING btree (_path);



CREATE INDEX lps_blocks_process_block_steps_order_idx ON cms.lps_blocks_process_block_steps USING btree (_order);



CREATE INDEX lps_blocks_process_block_steps_parent_id_idx ON cms.lps_blocks_process_block_steps USING btree (_parent_id);



CREATE INDEX lps_blocks_stats_block_items_order_idx ON cms.lps_blocks_stats_block_items USING btree (_order);



CREATE INDEX lps_blocks_stats_block_items_parent_id_idx ON cms.lps_blocks_stats_block_items USING btree (_parent_id);



CREATE INDEX lps_blocks_stats_block_order_idx ON cms.lps_blocks_stats_block USING btree (_order);



CREATE INDEX lps_blocks_stats_block_parent_id_idx ON cms.lps_blocks_stats_block USING btree (_parent_id);



CREATE INDEX lps_blocks_stats_block_path_idx ON cms.lps_blocks_stats_block USING btree (_path);



CREATE INDEX lps_blocks_takeaways_block_items_order_idx ON cms.lps_blocks_takeaways_block_items USING btree (_order);



CREATE INDEX lps_blocks_takeaways_block_items_parent_id_idx ON cms.lps_blocks_takeaways_block_items USING btree (_parent_id);



CREATE INDEX lps_blocks_takeaways_block_order_idx ON cms.lps_blocks_takeaways_block USING btree (_order);



CREATE INDEX lps_blocks_takeaways_block_parent_id_idx ON cms.lps_blocks_takeaways_block USING btree (_parent_id);



CREATE INDEX lps_blocks_takeaways_block_path_idx ON cms.lps_blocks_takeaways_block USING btree (_path);



CREATE INDEX lps_blocks_technology_image_upload_idx ON cms.lps_blocks_technology USING btree (image_upload_id);



CREATE INDEX lps_blocks_technology_order_idx ON cms.lps_blocks_technology USING btree (_order);



CREATE INDEX lps_blocks_technology_parent_id_idx ON cms.lps_blocks_technology USING btree (_parent_id);



CREATE INDEX lps_blocks_technology_path_idx ON cms.lps_blocks_technology USING btree (_path);



CREATE INDEX lps_blocks_testimonials_embed_filter_by_content_cat_idx ON cms.lps_blocks_testimonials_embed USING btree (filter_by_content_category_id);



CREATE INDEX lps_blocks_testimonials_embed_filter_by_treatment_idx ON cms.lps_blocks_testimonials_embed USING btree (filter_by_treatment_id);



CREATE INDEX lps_blocks_testimonials_embed_order_idx ON cms.lps_blocks_testimonials_embed USING btree (_order);



CREATE INDEX lps_blocks_testimonials_embed_parent_id_idx ON cms.lps_blocks_testimonials_embed USING btree (_parent_id);



CREATE INDEX lps_blocks_testimonials_embed_path_idx ON cms.lps_blocks_testimonials_embed USING btree (_path);



CREATE INDEX lps_blocks_text_section_order_idx ON cms.lps_blocks_text_section USING btree (_order);



CREATE INDEX lps_blocks_text_section_parent_id_idx ON cms.lps_blocks_text_section USING btree (_parent_id);



CREATE INDEX lps_blocks_text_section_path_idx ON cms.lps_blocks_text_section USING btree (_path);



CREATE INDEX lps_blocks_video_embed_order_idx ON cms.lps_blocks_video_embed USING btree (_order);



CREATE INDEX lps_blocks_video_embed_parent_id_idx ON cms.lps_blocks_video_embed USING btree (_parent_id);



CREATE INDEX lps_blocks_video_embed_path_idx ON cms.lps_blocks_video_embed USING btree (_path);



ALTER TABLE ONLY cms._lps_v_blocks_before_after_block_items
    ADD CONSTRAINT _lps_v_blocks_before_after_block_items_parent_id_fk FOREIGN KEY (_parent_id) REFERENCES cms._lps_v_blocks_before_after_block(id) ON DELETE CASCADE;



ALTER TABLE ONLY cms._lps_v_blocks_before_after_block
    ADD CONSTRAINT _lps_v_blocks_before_after_block_parent_id_fk FOREIGN KEY (_parent_id) REFERENCES cms._lps_v(id) ON DELETE CASCADE;



ALTER TABLE ONLY cms._lps_v_blocks_benefits_block_items
    ADD CONSTRAINT _lps_v_blocks_benefits_block_items_parent_id_fk FOREIGN KEY (_parent_id) REFERENCES cms._lps_v_blocks_benefits_block(id) ON DELETE CASCADE;



ALTER TABLE ONLY cms._lps_v_blocks_benefits_block
    ADD CONSTRAINT _lps_v_blocks_benefits_block_parent_id_fk FOREIGN KEY (_parent_id) REFERENCES cms._lps_v(id) ON DELETE CASCADE;



ALTER TABLE ONLY cms._lps_v_blocks_booking_form
    ADD CONSTRAINT _lps_v_blocks_booking_form_parent_id_fk FOREIGN KEY (_parent_id) REFERENCES cms._lps_v(id) ON DELETE CASCADE;



ALTER TABLE ONLY cms._lps_v_blocks_content_grid_items
    ADD CONSTRAINT _lps_v_blocks_content_grid_items_parent_id_fk FOREIGN KEY (_parent_id) REFERENCES cms._lps_v_blocks_content_grid(id) ON DELETE CASCADE;



ALTER TABLE ONLY cms._lps_v_blocks_content_grid
    ADD CONSTRAINT _lps_v_blocks_content_grid_parent_id_fk FOREIGN KEY (_parent_id) REFERENCES cms._lps_v(id) ON DELETE CASCADE;



ALTER TABLE ONLY cms._lps_v_blocks_cta_block
    ADD CONSTRAINT _lps_v_blocks_cta_block_parent_id_fk FOREIGN KEY (_parent_id) REFERENCES cms._lps_v(id) ON DELETE CASCADE;



ALTER TABLE ONLY cms._lps_v_blocks_data_table_columns
    ADD CONSTRAINT _lps_v_blocks_data_table_columns_parent_id_fk FOREIGN KEY (_parent_id) REFERENCES cms._lps_v_blocks_data_table(id) ON DELETE CASCADE;



ALTER TABLE ONLY cms._lps_v_blocks_data_table
    ADD CONSTRAINT _lps_v_blocks_data_table_parent_id_fk FOREIGN KEY (_parent_id) REFERENCES cms._lps_v(id) ON DELETE CASCADE;



ALTER TABLE ONLY cms._lps_v_blocks_data_table_rows_cells
    ADD CONSTRAINT _lps_v_blocks_data_table_rows_cells_parent_id_fk FOREIGN KEY (_parent_id) REFERENCES cms._lps_v_blocks_data_table_rows(id) ON DELETE CASCADE;



ALTER TABLE ONLY cms._lps_v_blocks_data_table_rows
    ADD CONSTRAINT _lps_v_blocks_data_table_rows_parent_id_fk FOREIGN KEY (_parent_id) REFERENCES cms._lps_v_blocks_data_table(id) ON DELETE CASCADE;



ALTER TABLE ONLY cms._lps_v_blocks_doctors_embed
    ADD CONSTRAINT _lps_v_blocks_doctors_embed_filter_by_content_category_id_ FOREIGN KEY (filter_by_content_category_id) REFERENCES cms.content_categories(id) ON DELETE SET NULL;



ALTER TABLE ONLY cms._lps_v_blocks_doctors_embed
    ADD CONSTRAINT _lps_v_blocks_doctors_embed_parent_id_fk FOREIGN KEY (_parent_id) REFERENCES cms._lps_v(id) ON DELETE CASCADE;



ALTER TABLE ONLY cms._lps_v_blocks_faqs_embed
    ADD CONSTRAINT _lps_v_blocks_faqs_embed_filter_by_content_category_id_con FOREIGN KEY (filter_by_content_category_id) REFERENCES cms.content_categories(id) ON DELETE SET NULL;



ALTER TABLE ONLY cms._lps_v_blocks_faqs_embed_inline_faqs
    ADD CONSTRAINT _lps_v_blocks_faqs_embed_inline_faqs_parent_id_fk FOREIGN KEY (_parent_id) REFERENCES cms._lps_v_blocks_faqs_embed(id) ON DELETE CASCADE;



ALTER TABLE ONLY cms._lps_v_blocks_faqs_embed
    ADD CONSTRAINT _lps_v_blocks_faqs_embed_parent_id_fk FOREIGN KEY (_parent_id) REFERENCES cms._lps_v(id) ON DELETE CASCADE;



ALTER TABLE ONLY cms._lps_v_blocks_html_embed
    ADD CONSTRAINT _lps_v_blocks_html_embed_parent_id_fk FOREIGN KEY (_parent_id) REFERENCES cms._lps_v(id) ON DELETE CASCADE;



ALTER TABLE ONLY cms._lps_v_blocks_image_slider_images
    ADD CONSTRAINT _lps_v_blocks_image_slider_images_parent_id_fk FOREIGN KEY (_parent_id) REFERENCES cms._lps_v_blocks_image_slider(id) ON DELETE CASCADE;



ALTER TABLE ONLY cms._lps_v_blocks_image_slider
    ADD CONSTRAINT _lps_v_blocks_image_slider_parent_id_fk FOREIGN KEY (_parent_id) REFERENCES cms._lps_v(id) ON DELETE CASCADE;



ALTER TABLE ONLY cms._lps_v_blocks_notice_block
    ADD CONSTRAINT _lps_v_blocks_notice_block__parent_id_fkey FOREIGN KEY (_parent_id) REFERENCES cms._lps_v(id) ON DELETE CASCADE;



ALTER TABLE ONLY cms._lps_v_blocks_overview_block_paragraphs
    ADD CONSTRAINT _lps_v_blocks_overview_block_paragraphs_parent_id_fk FOREIGN KEY (_parent_id) REFERENCES cms._lps_v_blocks_overview_block(id) ON DELETE CASCADE;



ALTER TABLE ONLY cms._lps_v_blocks_overview_block
    ADD CONSTRAINT _lps_v_blocks_overview_block_parent_id_fk FOREIGN KEY (_parent_id) REFERENCES cms._lps_v(id) ON DELETE CASCADE;



ALTER TABLE ONLY cms._lps_v_blocks_pricing_block
    ADD CONSTRAINT _lps_v_blocks_pricing_block_parent_id_fk FOREIGN KEY (_parent_id) REFERENCES cms._lps_v(id) ON DELETE CASCADE;



ALTER TABLE ONLY cms._lps_v_blocks_pricing_block_plans_features
    ADD CONSTRAINT _lps_v_blocks_pricing_block_plans_features_parent_id_fk FOREIGN KEY (_parent_id) REFERENCES cms._lps_v_blocks_pricing_block_plans(id) ON DELETE CASCADE;



ALTER TABLE ONLY cms._lps_v_blocks_pricing_block_plans
    ADD CONSTRAINT _lps_v_blocks_pricing_block_plans_parent_id_fk FOREIGN KEY (_parent_id) REFERENCES cms._lps_v_blocks_pricing_block(id) ON DELETE CASCADE;



ALTER TABLE ONLY cms._lps_v_blocks_process_block
    ADD CONSTRAINT _lps_v_blocks_process_block_parent_id_fk FOREIGN KEY (_parent_id) REFERENCES cms._lps_v(id) ON DELETE CASCADE;



ALTER TABLE ONLY cms._lps_v_blocks_process_block_steps
    ADD CONSTRAINT _lps_v_blocks_process_block_steps_parent_id_fk FOREIGN KEY (_parent_id) REFERENCES cms._lps_v_blocks_process_block(id) ON DELETE CASCADE;



ALTER TABLE ONLY cms._lps_v_blocks_stats_block_items
    ADD CONSTRAINT _lps_v_blocks_stats_block_items_parent_id_fk FOREIGN KEY (_parent_id) REFERENCES cms._lps_v_blocks_stats_block(id) ON DELETE CASCADE;



ALTER TABLE ONLY cms._lps_v_blocks_stats_block
    ADD CONSTRAINT _lps_v_blocks_stats_block_parent_id_fk FOREIGN KEY (_parent_id) REFERENCES cms._lps_v(id) ON DELETE CASCADE;



ALTER TABLE ONLY cms._lps_v_blocks_takeaways_block
    ADD CONSTRAINT _lps_v_blocks_takeaways_block__parent_id_fkey FOREIGN KEY (_parent_id) REFERENCES cms._lps_v(id) ON DELETE CASCADE;



ALTER TABLE ONLY cms._lps_v_blocks_takeaways_block_items
    ADD CONSTRAINT _lps_v_blocks_takeaways_block_items__parent_id_fkey FOREIGN KEY (_parent_id) REFERENCES cms._lps_v_blocks_takeaways_block(id) ON DELETE CASCADE;



ALTER TABLE ONLY cms._lps_v_blocks_technology
    ADD CONSTRAINT _lps_v_blocks_technology__parent_id_fkey FOREIGN KEY (_parent_id) REFERENCES cms._lps_v(id) ON DELETE CASCADE;



ALTER TABLE ONLY cms._lps_v_blocks_technology
    ADD CONSTRAINT _lps_v_blocks_technology_image_upload_id_fkey FOREIGN KEY (image_upload_id) REFERENCES cms.media(id) ON DELETE SET NULL;



ALTER TABLE ONLY cms._lps_v_blocks_testimonials_embed
    ADD CONSTRAINT _lps_v_blocks_testimonials_embed_filter_by_content_categor FOREIGN KEY (filter_by_content_category_id) REFERENCES cms.content_categories(id) ON DELETE SET NULL;



ALTER TABLE ONLY cms._lps_v_blocks_testimonials_embed
    ADD CONSTRAINT _lps_v_blocks_testimonials_embed_filter_by_treatment_id_tr FOREIGN KEY (filter_by_treatment_id) REFERENCES cms.treatments(id) ON DELETE SET NULL;



ALTER TABLE ONLY cms._lps_v_blocks_testimonials_embed
    ADD CONSTRAINT _lps_v_blocks_testimonials_embed_parent_id_fk FOREIGN KEY (_parent_id) REFERENCES cms._lps_v(id) ON DELETE CASCADE;



ALTER TABLE ONLY cms._lps_v_blocks_text_section
    ADD CONSTRAINT _lps_v_blocks_text_section_parent_id_fk FOREIGN KEY (_parent_id) REFERENCES cms._lps_v(id) ON DELETE CASCADE;



ALTER TABLE ONLY cms._lps_v_blocks_video_embed
    ADD CONSTRAINT _lps_v_blocks_video_embed_parent_id_fk FOREIGN KEY (_parent_id) REFERENCES cms._lps_v(id) ON DELETE CASCADE;



ALTER TABLE ONLY cms.lps_blocks_before_after_block_items
    ADD CONSTRAINT lps_blocks_before_after_block_items_parent_id_fk FOREIGN KEY (_parent_id) REFERENCES cms.lps_blocks_before_after_block(id) ON DELETE CASCADE;



ALTER TABLE ONLY cms.lps_blocks_before_after_block
    ADD CONSTRAINT lps_blocks_before_after_block_parent_id_fk FOREIGN KEY (_parent_id) REFERENCES cms.lps(id) ON DELETE CASCADE;



ALTER TABLE ONLY cms.lps_blocks_benefits_block_items
    ADD CONSTRAINT lps_blocks_benefits_block_items_parent_id_fk FOREIGN KEY (_parent_id) REFERENCES cms.lps_blocks_benefits_block(id) ON DELETE CASCADE;



ALTER TABLE ONLY cms.lps_blocks_benefits_block
    ADD CONSTRAINT lps_blocks_benefits_block_parent_id_fk FOREIGN KEY (_parent_id) REFERENCES cms.lps(id) ON DELETE CASCADE;



ALTER TABLE ONLY cms.lps_blocks_booking_form
    ADD CONSTRAINT lps_blocks_booking_form_parent_id_fk FOREIGN KEY (_parent_id) REFERENCES cms.lps(id) ON DELETE CASCADE;



ALTER TABLE ONLY cms.lps_blocks_content_grid_items
    ADD CONSTRAINT lps_blocks_content_grid_items_parent_id_fk FOREIGN KEY (_parent_id) REFERENCES cms.lps_blocks_content_grid(id) ON DELETE CASCADE;



ALTER TABLE ONLY cms.lps_blocks_content_grid
    ADD CONSTRAINT lps_blocks_content_grid_parent_id_fk FOREIGN KEY (_parent_id) REFERENCES cms.lps(id) ON DELETE CASCADE;



ALTER TABLE ONLY cms.lps_blocks_cta_block
    ADD CONSTRAINT lps_blocks_cta_block_parent_id_fk FOREIGN KEY (_parent_id) REFERENCES cms.lps(id) ON DELETE CASCADE;



ALTER TABLE ONLY cms.lps_blocks_data_table_columns
    ADD CONSTRAINT lps_blocks_data_table_columns_parent_id_fk FOREIGN KEY (_parent_id) REFERENCES cms.lps_blocks_data_table(id) ON DELETE CASCADE;



ALTER TABLE ONLY cms.lps_blocks_data_table
    ADD CONSTRAINT lps_blocks_data_table_parent_id_fk FOREIGN KEY (_parent_id) REFERENCES cms.lps(id) ON DELETE CASCADE;



ALTER TABLE ONLY cms.lps_blocks_data_table_rows_cells
    ADD CONSTRAINT lps_blocks_data_table_rows_cells_parent_id_fk FOREIGN KEY (_parent_id) REFERENCES cms.lps_blocks_data_table_rows(id) ON DELETE CASCADE;



ALTER TABLE ONLY cms.lps_blocks_data_table_rows
    ADD CONSTRAINT lps_blocks_data_table_rows_parent_id_fk FOREIGN KEY (_parent_id) REFERENCES cms.lps_blocks_data_table(id) ON DELETE CASCADE;



ALTER TABLE ONLY cms.lps_blocks_doctors_embed
    ADD CONSTRAINT lps_blocks_doctors_embed_filter_by_content_category_id_con FOREIGN KEY (filter_by_content_category_id) REFERENCES cms.content_categories(id) ON DELETE SET NULL;



ALTER TABLE ONLY cms.lps_blocks_doctors_embed
    ADD CONSTRAINT lps_blocks_doctors_embed_parent_id_fk FOREIGN KEY (_parent_id) REFERENCES cms.lps(id) ON DELETE CASCADE;



ALTER TABLE ONLY cms.lps_blocks_faqs_embed
    ADD CONSTRAINT lps_blocks_faqs_embed_filter_by_content_category_id_conten FOREIGN KEY (filter_by_content_category_id) REFERENCES cms.content_categories(id) ON DELETE SET NULL;



ALTER TABLE ONLY cms.lps_blocks_faqs_embed_inline_faqs
    ADD CONSTRAINT lps_blocks_faqs_embed_inline_faqs_parent_id_fk FOREIGN KEY (_parent_id) REFERENCES cms.lps_blocks_faqs_embed(id) ON DELETE CASCADE;



ALTER TABLE ONLY cms.lps_blocks_faqs_embed
    ADD CONSTRAINT lps_blocks_faqs_embed_parent_id_fk FOREIGN KEY (_parent_id) REFERENCES cms.lps(id) ON DELETE CASCADE;



ALTER TABLE ONLY cms.lps_blocks_html_embed
    ADD CONSTRAINT lps_blocks_html_embed_parent_id_fk FOREIGN KEY (_parent_id) REFERENCES cms.lps(id) ON DELETE CASCADE;



ALTER TABLE ONLY cms.lps_blocks_image_slider_images
    ADD CONSTRAINT lps_blocks_image_slider_images_parent_id_fk FOREIGN KEY (_parent_id) REFERENCES cms.lps_blocks_image_slider(id) ON DELETE CASCADE;



ALTER TABLE ONLY cms.lps_blocks_image_slider
    ADD CONSTRAINT lps_blocks_image_slider_parent_id_fk FOREIGN KEY (_parent_id) REFERENCES cms.lps(id) ON DELETE CASCADE;



ALTER TABLE ONLY cms.lps_blocks_notice_block
    ADD CONSTRAINT lps_blocks_notice_block__parent_id_fkey FOREIGN KEY (_parent_id) REFERENCES cms.lps(id) ON DELETE CASCADE;



ALTER TABLE ONLY cms.lps_blocks_overview_block_paragraphs
    ADD CONSTRAINT lps_blocks_overview_block_paragraphs_parent_id_fk FOREIGN KEY (_parent_id) REFERENCES cms.lps_blocks_overview_block(id) ON DELETE CASCADE;



ALTER TABLE ONLY cms.lps_blocks_overview_block
    ADD CONSTRAINT lps_blocks_overview_block_parent_id_fk FOREIGN KEY (_parent_id) REFERENCES cms.lps(id) ON DELETE CASCADE;



ALTER TABLE ONLY cms.lps_blocks_pricing_block
    ADD CONSTRAINT lps_blocks_pricing_block_parent_id_fk FOREIGN KEY (_parent_id) REFERENCES cms.lps(id) ON DELETE CASCADE;



ALTER TABLE ONLY cms.lps_blocks_pricing_block_plans_features
    ADD CONSTRAINT lps_blocks_pricing_block_plans_features_parent_id_fk FOREIGN KEY (_parent_id) REFERENCES cms.lps_blocks_pricing_block_plans(id) ON DELETE CASCADE;



ALTER TABLE ONLY cms.lps_blocks_pricing_block_plans
    ADD CONSTRAINT lps_blocks_pricing_block_plans_parent_id_fk FOREIGN KEY (_parent_id) REFERENCES cms.lps_blocks_pricing_block(id) ON DELETE CASCADE;



ALTER TABLE ONLY cms.lps_blocks_process_block
    ADD CONSTRAINT lps_blocks_process_block_parent_id_fk FOREIGN KEY (_parent_id) REFERENCES cms.lps(id) ON DELETE CASCADE;



ALTER TABLE ONLY cms.lps_blocks_process_block_steps
    ADD CONSTRAINT lps_blocks_process_block_steps_parent_id_fk FOREIGN KEY (_parent_id) REFERENCES cms.lps_blocks_process_block(id) ON DELETE CASCADE;



ALTER TABLE ONLY cms.lps_blocks_stats_block_items
    ADD CONSTRAINT lps_blocks_stats_block_items_parent_id_fk FOREIGN KEY (_parent_id) REFERENCES cms.lps_blocks_stats_block(id) ON DELETE CASCADE;



ALTER TABLE ONLY cms.lps_blocks_stats_block
    ADD CONSTRAINT lps_blocks_stats_block_parent_id_fk FOREIGN KEY (_parent_id) REFERENCES cms.lps(id) ON DELETE CASCADE;



ALTER TABLE ONLY cms.lps_blocks_takeaways_block
    ADD CONSTRAINT lps_blocks_takeaways_block__parent_id_fkey FOREIGN KEY (_parent_id) REFERENCES cms.lps(id) ON DELETE CASCADE;



ALTER TABLE ONLY cms.lps_blocks_takeaways_block_items
    ADD CONSTRAINT lps_blocks_takeaways_block_items__parent_id_fkey FOREIGN KEY (_parent_id) REFERENCES cms.lps_blocks_takeaways_block(id) ON DELETE CASCADE;



ALTER TABLE ONLY cms.lps_blocks_technology
    ADD CONSTRAINT lps_blocks_technology__parent_id_fkey FOREIGN KEY (_parent_id) REFERENCES cms.lps(id) ON DELETE CASCADE;



ALTER TABLE ONLY cms.lps_blocks_technology
    ADD CONSTRAINT lps_blocks_technology_image_upload_id_fkey FOREIGN KEY (image_upload_id) REFERENCES cms.media(id) ON DELETE SET NULL;



ALTER TABLE ONLY cms.lps_blocks_testimonials_embed
    ADD CONSTRAINT lps_blocks_testimonials_embed_filter_by_content_category_i FOREIGN KEY (filter_by_content_category_id) REFERENCES cms.content_categories(id) ON DELETE SET NULL;



ALTER TABLE ONLY cms.lps_blocks_testimonials_embed
    ADD CONSTRAINT lps_blocks_testimonials_embed_filter_by_treatment_id_treat FOREIGN KEY (filter_by_treatment_id) REFERENCES cms.treatments(id) ON DELETE SET NULL;



ALTER TABLE ONLY cms.lps_blocks_testimonials_embed
    ADD CONSTRAINT lps_blocks_testimonials_embed_parent_id_fk FOREIGN KEY (_parent_id) REFERENCES cms.lps(id) ON DELETE CASCADE;



ALTER TABLE ONLY cms.lps_blocks_text_section
    ADD CONSTRAINT lps_blocks_text_section_parent_id_fk FOREIGN KEY (_parent_id) REFERENCES cms.lps(id) ON DELETE CASCADE;



ALTER TABLE ONLY cms.lps_blocks_video_embed
    ADD CONSTRAINT lps_blocks_video_embed_parent_id_fk FOREIGN KEY (_parent_id) REFERENCES cms.lps(id) ON DELETE CASCADE;





COMMIT;
